alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias grok='man'
alias dcl='docker-compose logs'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dce='docker-compose exec'
alias dcd='docker-compose down'
alias dcp='docker-compose pull'